export const siteConfig = {
  name: "StackForgeAI",
  fullName: "StackForgeAI — Intelligent Software for Africa's Institutions",
  domain: "stackforgeai.africa",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://stackforgeai.africa",
  description:
    "StackForgeAI builds AI-powered systems, platforms, and digital infrastructure for governments, universities, and businesses, from Rwanda to the rest of the continent.",
  keywords: [
    "StackForgeAI",
    "software development Rwanda",
    "software company Kigali",
    "custom software Rwanda",
    "web development Kigali",
    "web development Rwanda",
    "mobile app development Rwanda",
    "AI company Rwanda",
    "AI solutions Rwanda",
    "artificial intelligence Kigali",
    "machine learning Rwanda",
    "digital transformation Rwanda",
    "enterprise software Rwanda",
    "government software Rwanda",
    "ICT Rwanda",
    "technology consulting Rwanda",
    "SaaS Rwanda",
    "cloud solutions Rwanda",
    "business automation Rwanda",
    "Education software Rwanda",
    "edtech Rwanda",
    "Education Platforms",
    "Rwanda tech startup",
    "Kigali software engineers",
    "Africa",
    "Rwanda",
    "Kigali",
    "Software development",
    "Digital infrastructure",
    "AI Systems",
    "Government Tech",
    "Custom Software",
    "Web Applications",
    "Automation",
  ],
  seo: {
    home: {
      title: "StackForgeAI | Software & AI Development in Rwanda & Kigali",
      description:
        "Leading software and AI company in Kigali, Rwanda: custom web & mobile apps, government and education platforms, digital transformation, and enterprise automation across Rwanda and Africa.",
    },
  },
  author: {
    name: "StackForgeAI",
    email: "hello@stackforgeai.africa",
    url: "https://stackforgeai.africa",
  },
  contact: {
    email: "hello@stackforgeai.africa",
    phone: process.env.NEXT_PUBLIC_PHONE_NUMBER ?? "+250799486531",
    phoneDisplay: process.env.NEXT_PUBLIC_PHONE_DISPLAY ?? "+250 799 486 531",
    whatsapp: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER ?? "+250799486531",
    whatsappDisplay: process.env.NEXT_PUBLIC_WHATSAPP_DISPLAY ?? "+250 799 486 531",
    location: "Kigali, Rwanda",
  },
  links: {
    calendly: process.env.NEXT_PUBLIC_CALENDLY_URL ?? "https://calendly.com/stackforgeai/demo",
    stackfix: "https://stackfix.app/dashboard",
    stackedu: "https://stackedu.app/dashboard",
    directory: "https://kgl.directory",
    github: "https://github.com/StackForgeAI-Projects",
  },
  nav: [
    { href: "#about", labelKey: "nav.about" },
    { href: "#products", labelKey: "nav.products" },
    { href: "#services", labelKey: "nav.services" },
    { href: "#impact", labelKey: "nav.impact" },
    { href: "#contact", labelKey: "nav.contact" },
  ] as const,
  ogImage: "/og-image.png",
} as const;

export type SiteConfig = typeof siteConfig;
